name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Fix permissions for Vite
      - name: Fix permissions for Vite
        run: chmod +x ./node_modules/.bin/vite

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Debug secrets (optional)
      - name: Debug Secrets
        run: |
          echo "FTP_HOST: ${{ secrets.FTP_HOST }}"
          echo "FTP_USERNAME: ${{ secrets.FTP_USERNAME }}"

      # Step 6: Deploy files to Hostinger via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: build/
          server-dir: public_html/
    
          